<?php
/**
 * @file
 * fs_f_fn_search_api.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function fs_f_fn_search_api_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['facetapi-0JIa547iRkG1o8gcUcEvP7OG60h81xDh'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '0JIa547iRkG1o8gcUcEvP7OG60h81xDh',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'advanced-search*',
    'roles' => array(),
    'themes' => array(
      'adaptivetheme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'adaptivetheme',
        'weight' => 0,
      ),
      'corposs' => array(
        'region' => 'left_sidebar',
        'status' => 1,
        'theme' => 'corposs',
        'weight' => -49,
      ),
      'mix_and_match' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'mix_and_match',
        'weight' => 0,
      ),
    ),
    'title' => 'Mandate Status',
    'visibility' => 1,
  );

  $export['facetapi-0U1vdHJPbRjrBDMAZsPnGjs3Vx4Crgf3'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '0U1vdHJPbRjrBDMAZsPnGjs3Vx4Crgf3',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'advanced-search*',
    'roles' => array(),
    'themes' => array(
      'adaptivetheme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'adaptivetheme',
        'weight' => 0,
      ),
      'corposs' => array(
        'region' => 'left_sidebar',
        'status' => 1,
        'theme' => 'corposs',
        'weight' => -46,
      ),
      'mix_and_match' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'mix_and_match',
        'weight' => 0,
      ),
    ),
    'title' => 'Geographic',
    'visibility' => 1,
  );

  $export['facetapi-6QSOd03dQY4zF0FaE2wqi1lse4QVH27E'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '6QSOd03dQY4zF0FaE2wqi1lse4QVH27E',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'advanced-search*',
    'roles' => array(),
    'themes' => array(
      'adaptivetheme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'adaptivetheme',
        'weight' => 0,
      ),
      'corposs' => array(
        'region' => 'left_sidebar',
        'status' => 1,
        'theme' => 'corposs',
        'weight' => -47,
      ),
      'mix_and_match' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'mix_and_match',
        'weight' => 0,
      ),
    ),
    'title' => 'Currency',
    'visibility' => 1,
  );

  $export['facetapi-6T31dcEVB3Uhrmn9zhmu7314qC7v9AtD'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '6T31dcEVB3Uhrmn9zhmu7314qC7v9AtD',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'advanced-search*',
    'roles' => array(),
    'themes' => array(
      'adaptivetheme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'adaptivetheme',
        'weight' => 0,
      ),
      'corposs' => array(
        'region' => 'left_sidebar',
        'status' => 1,
        'theme' => 'corposs',
        'weight' => -45,
      ),
      'mix_and_match' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'mix_and_match',
        'weight' => 0,
      ),
    ),
    'title' => 'Office Type',
    'visibility' => 1,
  );

  $export['facetapi-7fM0beGA0Fy3wocPaJBZgVjtILY1RtI9'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '7fM0beGA0Fy3wocPaJBZgVjtILY1RtI9',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'advanced-search*',
    'roles' => array(),
    'themes' => array(
      'adaptivetheme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'adaptivetheme',
        'weight' => 0,
      ),
      'corposs' => array(
        'region' => 'left_sidebar',
        'status' => 1,
        'theme' => 'corposs',
        'weight' => -50,
      ),
      'mix_and_match' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'mix_and_match',
        'weight' => 0,
      ),
    ),
    'title' => 'Major/Minor Style',
    'visibility' => 1,
  );

  $export['facetapi-8lDyhY0AIm2CjRmcoLQbYuHss3I3Qv03'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '8lDyhY0AIm2CjRmcoLQbYuHss3I3Qv03',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'advanced-search*',
    'roles' => array(),
    'themes' => array(
      'adaptivetheme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'adaptivetheme',
        'weight' => 0,
      ),
      'corposs' => array(
        'region' => 'left_sidebar',
        'status' => 1,
        'theme' => 'corposs',
        'weight' => -43,
      ),
      'mix_and_match' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'mix_and_match',
        'weight' => 0,
      ),
    ),
    'title' => 'Plan Size',
    'visibility' => 1,
  );

  $export['facetapi-D7KpQw1g4ijNyOsqYiUwyIVVrfcz6LfZ'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'D7KpQw1g4ijNyOsqYiUwyIVVrfcz6LfZ',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'advanced-search*',
    'roles' => array(),
    'themes' => array(
      'adaptivetheme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'adaptivetheme',
        'weight' => 0,
      ),
      'corposs' => array(
        'region' => 'left_sidebar',
        'status' => 1,
        'theme' => 'corposs',
        'weight' => -48,
      ),
      'mix_and_match' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'mix_and_match',
        'weight' => 0,
      ),
    ),
    'title' => 'Consultant Firm',
    'visibility' => 1,
  );

  $export['facetapi-LlXmtelmeJoU4kr1esoWjHgEE1010a20'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'LlXmtelmeJoU4kr1esoWjHgEE1010a20',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'advanced-search*',
    'roles' => array(),
    'themes' => array(
      'adaptivetheme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'adaptivetheme',
        'weight' => 0,
      ),
      'corposs' => array(
        'region' => 'left_sidebar',
        'status' => 1,
        'theme' => 'corposs',
        'weight' => -43,
      ),
      'mix_and_match' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'mix_and_match',
        'weight' => 0,
      ),
    ),
    'title' => 'Plan',
    'visibility' => 1,
  );

  $export['facetapi-Lwvgp6spBxvRZV3Q19NutXKMT3LX16se'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'Lwvgp6spBxvRZV3Q19NutXKMT3LX16se',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'advanced-search*',
    'roles' => array(),
    'themes' => array(
      'adaptivetheme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'adaptivetheme',
        'weight' => 0,
      ),
      'corposs' => array(
        'region' => 'left_sidebar',
        'status' => 1,
        'theme' => 'corposs',
        'weight' => -51,
      ),
      'mix_and_match' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'mix_and_match',
        'weight' => 0,
      ),
    ),
    'title' => 'Account Size',
    'visibility' => 1,
  );

  $export['facetapi-VbQdzVnvPY8QqwE5FcQT0qecky7UZBgQ'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'VbQdzVnvPY8QqwE5FcQT0qecky7UZBgQ',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'advanced-search*',
    'roles' => array(),
    'themes' => array(
      'adaptivetheme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'adaptivetheme',
        'weight' => 0,
      ),
      'corposs' => array(
        'region' => 'left_sidebar',
        'status' => 1,
        'theme' => 'corposs',
        'weight' => -42,
      ),
      'mix_and_match' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'mix_and_match',
        'weight' => 0,
      ),
    ),
    'title' => 'Plan Type',
    'visibility' => 1,
  );

  $export['facetapi-v3wXsXMozBnc8hWjP5HqkGVNYHnJzNMU'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'v3wXsXMozBnc8hWjP5HqkGVNYHnJzNMU',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'advanced-search*',
    'roles' => array(),
    'themes' => array(
      'adaptivetheme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'adaptivetheme',
        'weight' => 0,
      ),
      'corposs' => array(
        'region' => 'left_sidebar',
        'status' => 1,
        'theme' => 'corposs',
        'weight' => -53,
      ),
      'mix_and_match' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'mix_and_match',
        'weight' => 0,
      ),
    ),
    'title' => 'Content Type',
    'visibility' => 1,
  );

  $export['facetapi-yGFxP10FLH21PtFupsQzn3grEzCC5KaS'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'yGFxP10FLH21PtFupsQzn3grEzCC5KaS',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => 'advanced-search*',
    'roles' => array(),
    'themes' => array(
      'adaptivetheme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'adaptivetheme',
        'weight' => 0,
      ),
      'corposs' => array(
        'region' => 'left_sidebar',
        'status' => 1,
        'theme' => 'corposs',
        'weight' => -44,
      ),
      'mix_and_match' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'mix_and_match',
        'weight' => 0,
      ),
    ),
    'title' => 'News Type',
    'visibility' => 1,
  );

  $export['search_api_saved_searches-solr_index'] = array(
    'cache' => 5,
    'custom' => 0,
    'delta' => 'solr_index',
    'module' => 'search_api_saved_searches',
    'node_types' => array(),
    'pages' => 'advanced-search*',
    'roles' => array(),
    'themes' => array(
      'adaptivetheme' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'adaptivetheme',
        'weight' => 0,
      ),
      'corposs' => array(
        'region' => 'right_sidebar',
        'status' => 1,
        'theme' => 'corposs',
        'weight' => -52,
      ),
      'mix_and_match' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'mix_and_match',
        'weight' => 0,
      ),
    ),
    'title' => 'Saved Searches',
    'visibility' => 1,
  );

  return $export;
}
